# Generated by Django 3.1.4 on 2021-01-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_space', models.IntegerField(default=25)),
                ('floor_number', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('col', models.PositiveSmallIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('ticket_id', models.CharField(blank=True, max_length=256, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.floor')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=256, unique=True)),
                ('entered_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[(0, 'parked'), (1, 'exit')], max_length=50)),
                ('ticket_id', models.CharField(blank=True, max_length=256, null=True)),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspot')),
            ],
        ),
    ]
